version: '3.9'

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    restart: on-failure
    env_file: .env
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - BOT_TOKEN=${BOT_TOKEN}
      - RAPIDAPI_KEY=${RAPID_API_KEY}
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
    pg_data: